/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMembershipsRouteImport } from './routes/_app/memberships'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppMessagesUserIdRouteImport } from './routes/_app/messages.$userId'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events.$eventId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMembershipsRoute = AppMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesUserIdRoute = AppMessagesUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/community': typeof AppCommunityRoute
  '/discover': typeof AppDiscoverRoute
  '/events': typeof AppEventsRouteWithChildren
  '/memberships': typeof AppMembershipsRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/tickets': typeof AppTicketsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/messages/$userId': typeof AppMessagesUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/community': typeof AppCommunityRoute
  '/discover': typeof AppDiscoverRoute
  '/events': typeof AppEventsRouteWithChildren
  '/memberships': typeof AppMembershipsRoute
  '/messages': typeof AppMessagesRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/tickets': typeof AppTicketsRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/messages/$userId': typeof AppMessagesUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/events': typeof AppEventsRouteWithChildren
  '/_app/memberships': typeof AppMembershipsRoute
  '/_app/messages': typeof AppMessagesRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/messages/$userId': typeof AppMessagesUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/community'
    | '/discover'
    | '/events'
    | '/memberships'
    | '/messages'
    | '/profile'
    | '/tickets'
    | '/events/$eventId'
    | '/messages/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/community'
    | '/discover'
    | '/events'
    | '/memberships'
    | '/messages'
    | '/profile'
    | '/tickets'
    | '/events/$eventId'
    | '/messages/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/_app/community'
    | '/_app/discover'
    | '/_app/events'
    | '/_app/memberships'
    | '/_app/messages'
    | '/_app/profile'
    | '/_app/tickets'
    | '/_app/events/$eventId'
    | '/_app/messages/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memberships': {
      id: '/_app/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AppMembershipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/$userId': {
      id: '/_app/messages/$userId'
      path: '/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof AppMessagesUserIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
  }
}

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppMessagesRouteChildren {
  AppMessagesUserIdRoute: typeof AppMessagesUserIdRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesUserIdRoute: AppMessagesUserIdRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppMembershipsRoute: typeof AppMembershipsRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppTicketsRoute: typeof AppTicketsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppMembershipsRoute: AppMembershipsRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppTicketsRoute: AppTicketsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
